version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test_backend:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: cd backend && npm test
          name: Run backend tests
  build_frontend:
    executor: node/default
    steps:
      - run:
          command: cd frontend && npm run build
          name: Build frontend
workflows:
  test_and_build:
    jobs:
      - test_backend
      - build_frontend:
          requires:
            - test_backend
          filters:
            branches:
              only: main
