version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5
  node: circleci/node@5.1.0
jobs:
  test_backend:
    executor: node/default
    steps:
      - checkout
      - run:
          command: cd backend && npm i
          name: Install packages
      - run:
          command: cd backend && npm test
          name: Run backend tests
      - codecov/upload:
          file: ./backend/coverage/lcov-report
  build_frontend:
    executor: node/default
    steps:
      - checkout
      - run:
          command: cd frontend && npm i
          name: Install packages
      - run:
          command: cd frontend && npm run build
          name: Build frontend
      - run:
          command: mv frontend/build/ backend/
          name: Move built files to backend dir
workflows:
  test_and_build:
    jobs:
      - test_backend
      - build_frontend:
          requires:
            - test_backend
