version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test_backend:
    executor: node/default
    steps:
      - checkout
      - run:
          command: cd backend && npm i
          name: Install packages
      - run:
          command: cd backend && npm test
          name: Run backend tests
      - run:
          command: cd backend && npm run coverage
          name: Code coverage
  build_frontend:
    executor: node/default
    steps:
      - checkout
      - run:
          command: cd frontend && npm i
          name: Install packages
      - run:
          command: cd frontend && npm run build
          name: Build frontend
      - run:
          command: mv frontend/build/ backend/
          name: Move built files to backend dir
  build_docker_image:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            TAG=2.0.0.$CIRCLE_BUILD_NUM
            docker build -t cerberus:$TAG Dockerfile
workflows:
  test_and_build:
    jobs:
      - test_backend
      - build_frontend:
          requires:
            - test_backend
  build_image:
    jobs:
      - build_docker_image:
          filters:
            branches:
              only: feature/containerise
