openapi: 3.0.0
info:
  title: CERBERUS API
  description: API definition for the CERBERUS implant-management API.
  version: 0.0.1
paths:
  /implants/:
    get:
      summary: Retrieves all implants.
      tags:
        - Implants
      responses:
        "200": # status code
          description: Implant details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  implants:
                    type: array
                    description: This will be empty
                  errors:
                    type: array
                    items:
                      type: string
        "500": # status code
          description: An unexpected server-side error
          content:
            application/json:
              schema:
                type: object
                properties:
                  implants:
                    type: array
                    description: This will be empty
                  errors:
                    type: array
                    items:
                      type: string
